name = "Cafe"
description = "blog theme"
license = "MIT"
homepage = "https://github.com/owlzou/zola-theme-cafe"
# The minimum version of Zola required
min_version = "0.4.0"
# An optional live demo URL
demo = ""

# Any variable there can be overriden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# Site start year
copyright_start_year = "2019"

# Show grass svg
decoration = true

# Navigation 
# Use icon name from featherIcon https://feathericons.com/
nav = [
    {icon="feather",title="Blog",url="/posts"},
    {icon="archive",title="Archive",url="/archives"},
    {icon="star",title="Project",url="/projects"},
    {icon="alert-circle",title="About",url="/about"},
    {icon="tag",title="Taxonomies",url="/taxonomies"},
]

# Utterances: A lightweight comments widget built on GitHub issues. 
# https://utteranc.es/
[extra.utterances]
enable = false
repo=""
issue_term="pathname"
theme="github-light"
crossorigin="anonymous"

# For `projects page`, put toml in content/projects/data.toml
# File content like:
# 
# [[projects]]
# title = ""
# link = ""
# cover = ""
# description=""

# The theme author info: you!
[author]
name = "Owlzou"
homepage = "https://github.com/owlzou/"

